#!/usr/bin/env bash
# ============================================================================
# Phoneme SDLC Platform — Standard Project Scaffold
#
# Creates the frozen repository layout (BRD/PRD Section 18.1) for a Phoneme
# project on the staging server, ready to be pushed to its GitHub remote
# under the myphoneme organization.
#
# Usage:
#   ./setup-phoneme-project.sh \
#       --name "Teamora HRMS" \
#       --code TMRA \
#       --github-remote git@github.com:myphoneme/teamora-hrms.git \
#       --staging-url https://teamora-hrms.staging.phoneme.internal \
#       [--path /opt/phoneme/projects/teamora-hrms] \
#       [--platform-core-version 1.0.0]
#
# Only --name, --code and --github-remote are required. If --path is
# omitted, the project is created as ./<slugified-name> in the current
# directory. Re-running against an existing path is safe — it never
# overwrites a file that already exists, so a scaffold can be re-applied
# after a Skills-repo upgrade without clobbering project content.
# ============================================================================

set -euo pipefail

PRODUCT_NAME=""
PRODUCT_CODE=""
GITHUB_REMOTE=""
STAGING_URL=""
PROJECT_PATH=""
PLATFORM_CORE_VERSION="unset"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) PRODUCT_NAME="$2"; shift 2 ;;
    --code) PRODUCT_CODE="$2"; shift 2 ;;
    --github-remote) GITHUB_REMOTE="$2"; shift 2 ;;
    --staging-url) STAGING_URL="$2"; shift 2 ;;
    --path) PROJECT_PATH="$2"; shift 2 ;;
    --platform-core-version) PLATFORM_CORE_VERSION="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$PRODUCT_NAME" || -z "$PRODUCT_CODE" || -z "$GITHUB_REMOTE" ]]; then
  echo "Usage: $0 --name \"Product Name\" --code CODE --github-remote <url> [--staging-url <url>] [--path <dir>] [--platform-core-version <ver>]" >&2
  exit 1
fi

slugify() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g'; }

if [[ -z "$PROJECT_PATH" ]]; then
  PROJECT_PATH="./$(slugify "$PRODUCT_NAME")"
fi

echo "Scaffolding '$PRODUCT_NAME' ($PRODUCT_CODE) at: $PROJECT_PATH"

mkdir -p "$PROJECT_PATH"/docs/00-discovery
mkdir -p "$PROJECT_PATH"/docs/01-requirements
mkdir -p "$PROJECT_PATH"/docs/02-technical-design
mkdir -p "$PROJECT_PATH"/docs/03-change-requests
mkdir -p "$PROJECT_PATH"/src
mkdir -p "$PROJECT_PATH"/.sdlc

write_if_absent() {
  local f="$1"; shift
  if [[ -f "$f" ]]; then
    echo "  skip (exists): $f"
  else
    cat > "$f"
    echo "  created:       $f"
  fi
}

# ---------------------------------------------------------------------------
# .sdlc/project.json — Section 18.1
# ---------------------------------------------------------------------------
write_if_absent "$PROJECT_PATH/.sdlc/project.json" <<JSON
{
  "product_name": "$PRODUCT_NAME",
  "product_code": "$PRODUCT_CODE",
  "staging_url": "${STAGING_URL:-"TBD"}",
  "github_remote": "$GITHUB_REMOTE",
  "status": "onboarding",
  "onboarding_path": "new",
  "platform_core_version": "$PLATFORM_CORE_VERSION",
  "skills_repo": "phoneme-sdlc-skills",
  "skills_version": "unset",
  "created": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
JSON

# ---------------------------------------------------------------------------
# .sdlc/req-index.json — Section 18.1 (empty index; populated by the
# BRD/PRD Manager as requirements are drafted/approved/frozen)
# ---------------------------------------------------------------------------
write_if_absent "$PROJECT_PATH/.sdlc/req-index.json" <<'JSON'
{
  "requirements": []
}
JSON

# ---------------------------------------------------------------------------
# docs/ placeholders — one README per stage so the empty tree is
# self-documenting and git-trackable (git does not track empty dirs)
# ---------------------------------------------------------------------------
write_if_absent "$PROJECT_PATH/docs/00-discovery/README.md" <<'MD'
# 00 — Discovery

Discovery chat transcript, competitive research notes, and brand/theme
decisions from the Idea-to-BRD/PRD Wizard's Discovery Chat and User Flow
stages (BRD/PRD Section 3).
MD

write_if_absent "$PROJECT_PATH/docs/01-requirements/README.md" <<'MD'
# 01 — Requirements

BRD/PRD content, organized by module, REQ-ID indexed. Each requirement's
lifecycle state (Draft → Review ⇄ Needs Clarification → Approved → Frozen)
is tracked in `.sdlc/req-index.json`.
MD

write_if_absent "$PROJECT_PATH/docs/02-technical-design/README.md" <<'MD'
# 02 — Technical Design

Per module: data schema, process flow, microservices, and UI/UX dataflow
sub-documents, plus the parent Technical Design document — generated by the
phoneme-sdlc-skills Technical Design skill set.
MD

write_if_absent "$PROJECT_PATH/docs/03-change-requests/README.md" <<'MD'
# 03 — Change Requests

One record per Change Request, referencing the REQ-ID(s) it impacts
(BRD/PRD Section 18.4). Each CR's impact evaluation determines which
downstream documents regenerate automatically vs. flag for manual
regeneration.
MD

write_if_absent "$PROJECT_PATH/src/README.md" <<MD
# src

Application source for $PRODUCT_NAME. Framework choice is per-project
(the pilot uses FastAPI + React-Vite, per BRD/PRD Section 18.7).
MD

write_if_absent "$PROJECT_PATH/README.md" <<MD
# $PRODUCT_NAME

Product code: **$PRODUCT_CODE**
GitHub remote: $GITHUB_REMOTE

Scaffolded to the Phoneme SDLC Platform standard repository layout
(BRD/PRD Section 18.1). See \`docs/\` for requirements and design, and
\`.sdlc/project.json\` for platform metadata.
MD

echo ""
echo "Done. Next steps:"
echo "  cd $PROJECT_PATH"
echo "  git init   # if this is a brand-new repository"
echo "  git remote add origin $GITHUB_REMOTE"
echo "  git add . && git commit -m \"Scaffold: standard Phoneme SDLC project layout\""
echo "  git push -u origin main"
